// Data artikel blog umum Clincoo (blog.clincoo.buzz)
// Artikel baru: buat folder /<slug>/index.html lalu tambah entri di sini.
// Urut otomatis dari yang terbaru (field date).
window.blogArticles = [];
window.blogArticles.push({ slug: "openai-dari-chatgpt-ke-gpt", title: "OpenAI Lengkap: Sejarah, ChatGPT, Keluarga GPT, dan Ekosistemnya", desc: "Mengenal OpenAI dari akarnya: kisah berdirinya, ledakan ChatGPT, keluarga model GPT hingga DALL·E dan Whisper, kelebihan dan kekurangannya, serta untuk siapa OpenAI paling cocok.", date: "2026-10-05" });
window.blogArticles.push({ slug: "google-gemini-ai-lengkap", title: "Google Gemini Lengkap: dari Riset Transformer hingga AI di Semua Produk Google", desc: "Mengenal Google Gemini secara utuh: akar riset Google yang menemukan Transformer, integrasi AI di Search hingga Android, keluarga model Gemini dan Gemma, kelebihan, kekurangan, dan untuk siapa paling cocok.", date: "2026-10-05" });
window.blogArticles.push({ slug: "anthropic-claude-ai-lengkap", title: "Anthropic Claude Lengkap: AI yang Dibangun dengan Keamanan di Depan", desc: "Mengenal Anthropic dan keluarga Claude: didirikan alumni OpenAI dengan prinsip safety-first, unggul di analisis dokumen panjang dan coding, plus kelebihan, kekurangan, dan untuk siapa paling cocok.", date: "2026-10-05" });
window.blogArticles.push({ slug: "meta-llama-ai-lengkap", title: "Meta Llama Lengkap: Mesin di Balik Gelombang AI Terbuka", desc: "Mengenal Meta AI dan Llama: kenapa Meta membagikan bobot modelnya gratis, dampaknya ke industri dan startup, kelebihan, kekurangan, dan untuk siapa Llama paling cocok.", date: "2026-10-05" });
window.blogArticles.push({ slug: "xai-grok-lengkap", title: "xAI Grok Lengkap: AI Blak-blakan dari Elon Musk", desc: "Mengenal xAI dan Grok: latar belakang perusahaan Elon Musk, gaya khas Grok yang santai dan terhubung real-time dengan X, kelebihan, kekurangan, dan untuk siapa paling cocok.", date: "2026-10-05" });
window.blogArticles.push({ slug: "mistral-ai-lengkap", title: "Mistral AI Lengkap: Model Ringan Eropa yang Efisien", desc: "Mengenal Mistral AI: startup Prancis yang membuktikan model besar bukan satu-satunya jalan, lewat model efisien yang murah dan sebagian terbuka.", date: "2026-10-05" });
window.blogArticles.push({ slug: "deepseek-ai-lengkap", title: "DeepSeek Lengkap: Model Hemat Biaya yang Mengguncang Industri", desc: "Mengenal DeepSeek: lab AI dari Tiongkok yang mengejutkan dunia dengan model murah tapi kuat, strategi pelatihan efisien, dan rilis bobot terbuka.", date: "2026-10-05" });
window.blogArticles.push({ slug: "alibaba-qwen-lengkap", title: "Qwen Alibaba Lengkap: Keluarga Model Terbuka dari Asia", desc: "Mengenal keluarga Qwen dari Alibaba: raksasa e-commerce yang diam-diam membangun salah satu keluarga model terbuka paling lengkap di dunia.", date: "2026-10-05" });
